services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://mongo:27017/create-user
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ${PWD}/mongo-data:/data/db

volumes:
  mongo-data:
